"use client";

import Link from "next/link";
import type { BrowserDraft } from "@/lib/browser-draft";
import type { PublicationIssue } from "@/lib/publication-validation";
import { MAX_PROJECTS } from "@/lib/portfolio-snapshot";
import { AttentionIcon, FeedbackScope } from "./DraftFeedback";
import { ProjectFields } from "./StudioFields";

const studioSections = ["Your name", "Headshot", "Biography", "Education", "Tools", "Experience", "Homepage", "Projects", "Publish"];

export function StudioHeader({ storageFailed, signedIn, cloudStatus, saved, locked, preview }: { storageFailed: boolean; signedIn: boolean; cloudStatus: string; saved: boolean; locked: boolean; preview: () => void }) {
  return <header className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-6 py-4 md:px-10"><Link className="display text-xl font-semibold" href="/">Portfolio studio<span className="text-coral">.</span></Link><div className="flex flex-wrap items-center gap-4"><span className="text-sm text-moss" role="status">{storageFailed ? "Not saved · download a backup" : signedIn ? cloudStatus || "Saved on this device—sync pending" : saved ? "Saved on this device" : "Saving on this device…"}</span><button className="btn-secondary" disabled={locked} onClick={preview}>Preview portfolio</button></div></header>;
}

export function StudioSidebar({ section, issues, locked, recoveries, navigate, download, importBackup, removeUnused }: { section: number; issues: PublicationIssue[]; locked: boolean; recoveries: BrowserDraft[]; navigate: (section: number) => void; download: (draft?: BrowserDraft) => void; importBackup: (file?: File) => void; removeUnused: () => void }) {
  return <aside className="contents lg:block"><nav aria-label="Portfolio setup" className="grid grid-cols-2 gap-1 min-[375px]:grid-cols-3 sm:grid-cols-5 lg:grid-cols-1">{studioSections.map((label, i) => <button type="button" key={label} className={section === i ? "setup-step active" : "setup-step"} aria-current={section === i ? "step" : undefined} disabled={locked} onClick={() => navigate(i)}><span className="mono text-xs">{String(i + 1).padStart(2, "0")}</span><span>{label}</span>{issues.some(issue => issue.section === i) && <><AttentionIcon /><span className="sr-only">Needs attention</span></>}</button>)}</nav><details className="order-3 mt-3 space-y-3 border-t border-line pt-4 lg:order-none"><summary className="cursor-pointer text-sm font-bold">Draft backups & storage</summary><p className="text-sm leading-6 text-moss">Account drafts open automatically when you sign in, including on a new device. Offline edits and guest drafts stay on this device until synced. Download a backup before clearing browser data while sync is pending.</p><button className="btn-text" onClick={() => download()}>Download draft backup</button>{recoveries.map((value, i) => <button key={i} className="btn-text block" onClick={() => download(value)}>Download recovery {i + 1} · {new Date(value.updatedAt).toLocaleString()}</button>)}<label className="block text-sm font-bold">Import draft backup<input className="mt-2 block w-full text-sm" type="file" accept=".json,application/json" disabled={locked} onChange={event => { const file = event.target.files?.[0]; event.target.value = ""; importBackup(file); }} /></label><button className="btn-text" disabled={locked} onClick={removeUnused}>Remove unused draft images</button></details></aside>;
}

export function ProjectsPanel({ draft, projectStep, locked, setProjectStep, update, setUploading, clearError, newProject, commitProject }: { draft: BrowserDraft; projectStep: number; locked: boolean; setProjectStep: (step: number) => void; update: (change: Partial<BrowserDraft>) => void; setUploading: (busy: boolean) => void; clearError: () => void; newProject: () => void; commitProject: () => void }) {
  if (draft.projectDraft) return <div className="space-y-6"><div className="flex flex-wrap gap-2">{["Details", "Images", "Review"].map((name, i) => <button className={projectStep === i ? "section-tab active" : "section-tab"} aria-pressed={projectStep === i} disabled={locked} key={name} onClick={() => { setProjectStep(i); clearError(); }}>{name}</button>)}</div><fieldset disabled={locked}><FeedbackScope.Provider value={`project.${draft.projectDraft.id}`}><ProjectFields key={draft.projectDraft.id + projectStep} project={draft.projectDraft} section={projectStep} onChange={projectDraft => update({ projectDraft })} onBusy={setUploading} /></FeedbackScope.Provider></fieldset><div className="flex flex-wrap gap-3"><button className="btn-primary" disabled={locked} onClick={() => projectStep < 2 ? (setProjectStep(projectStep + 1), clearError()) : commitProject()}>{projectStep < 2 ? "Continue" : "Save project to draft"}</button><button className="btn-text" disabled={locked} onClick={() => { if (window.confirm("Discard this unfinished project edit? Saved projects will stay in your draft.")) update({ projectDraft: null }); }}>Discard project draft</button></div></div>;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="display text-2xl">Your projects <span className="text-moss">({draft.projects.length}/{MAX_PROJECTS})</span></h2><button className="btn-primary" onClick={newProject}>Add project</button></div>{!draft.projects.length && <p className="empty-note">Start with a project you are proud of. Add a description, images, and the tools you used.</p>}{draft.projects.map(project => <article className="rounded-xl border border-line p-5" key={project.id}><h3 className="text-lg font-bold">{project.title}</h3><p className="mt-1 text-sm text-moss">{project.images.length} images{project.featured ? " · Featured project" : ""}</p><div className="mt-4 flex flex-wrap gap-4"><button className="btn-secondary" onClick={() => { update({ projectDraft: project }); setProjectStep(0); }}>Edit {project.title}</button><button className="btn-text" onClick={() => update({ projects: draft.projects.map(p => ({ ...p, featured: p.id === project.id ? !project.featured : false })) })}>{project.featured ? "Remove feature" : "Feature project"}</button><button className="btn-text" onClick={() => { if (window.confirm(`Delete “${project.title}” from your draft? It stays online until you publish updates.`)) update({ projects: draft.projects.filter(p => p.id !== project.id) }); }}>Delete {project.title}</button></div></article>)}</div>;
}
