import Image from "next/image";
import Link from "next/link";
import { showcaseProfile, showcaseProjects } from "@/lib/showcase";
import { CreatorCount } from "./CreatorCount";
const steps = [
  ["Create your account", "A little space that’s yours. Sign up for free and start with a blank portfolio."],
  ["Tell your story", "Add your profile, education, experience, and the tools you love. One guided step at a time."],
  ["Bring your work to life", "Add projects, images, and the details behind your process. Choose a favorite to feature."],
  ["Preview. Publish. Share.", "See your site take shape, verify your email, and publish to your own portfolio link."],
];
const features = [
  ["01", "The person behind the work", "Your name, biography, and headshot. Give people a feel for who you are and how you think.", "Name / Biography / Headshot"],
  ["02", "A memorable first impression", "Make your homepage yours with a personal tagline, a banner image, and a featured project.", "Tagline / Banner / Featured work"],
  ["03", "Projects with a story to tell", "Go beyond a thumbnail. Share project dates, descriptions, image galleries, captions, and external links.", "Case studies / Galleries / Links"],
  ["04", "Every chapter of your career", "Show where you’ve worked, your roles, dates, and what you brought to each team or collaboration.", "Jobs / Roles / Experience"],
  ["05", "What shaped your practice", "Add schools, degrees, fields of study, dates, and descriptions of what you learned along the way.", "Education / Courses / Learning"],
  ["06", "The tools of your trade", "Choose software from the catalog or add your own tools. Include the technologies behind each project, too.", "Software / Tools / Technologies"],
];
export function LandingPage() {
  return <div className="landing-page">
    <header className="landing-nav landing-container"><Link href="/" className="display text-2xl font-semibold tracking-tight">Portfolio studio<span className="text-accent">.</span></Link><nav aria-label="Main navigation" className="flex flex-wrap items-center gap-x-6 gap-y-3 text-sm"><a className="public-nav hidden lg:inline-block" href="#how-it-works">How it works</a><a className="public-nav hidden lg:inline-block" href="#personalize">What you can personalize</a><Link className="public-nav" href="/login">Sign in</Link><Link className="btn-primary" href="/signup">Create your free portfolio <span aria-hidden="true">↗</span></Link></nav></header>
    <main id="main-content">
      <section className="landing-container landing-hero"><div className="hero-copy animate-rise"><p className="eyebrow flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-accent" />Your story. Your work. Your own website.</p><h1 className="display mt-7 text-[clamp(3.25rem,5.5vw,5.6rem)] leading-[1.06] tracking-[-.035em]">Your work deserves <i className="text-moss">a place of its own.</i></h1><p className="mt-7 max-w-lg text-lg leading-8 text-moss">Turn your projects and experience into a portfolio you’re proud to share. A few guided steps, a thoughtful design, and a space that feels like you.</p><div className="mt-8 flex flex-wrap items-center gap-5"><Link className="btn-primary" href="/signup">Create your free portfolio <span aria-hidden="true">↗</span></Link><a className="btn-text" href="#how-it-works">See how it works <span aria-hidden="true">↓</span></a></div><p className="mono mt-5 text-xs text-moss">100% free. No credit card. No coding.</p></div>
        <figure className="landing-preview animate-rise-delay"><figcaption className="flex items-center justify-between gap-3 px-5 py-4 mono text-[10px] uppercase tracking-widest text-moss"><span>A little look at what’s possible</span><span>Example portfolio</span></figcaption><div className="preview-sheet"><div className="flex items-center justify-between border-b border-line pb-4"><span className="display text-lg">{showcaseProfile.name}<span className="text-accent">.</span></span><span className="mono text-[10px] text-moss">WORK &nbsp; / &nbsp; ABOUT</span></div><p className="eyebrow mt-7">Independent product designer</p><p className="display my-4 text-[clamp(1.9rem,3vw,2.6rem)] leading-tight">Good ideas.<br /><i>Thoughtfully made.</i></p><Image src={showcaseProjects[0].thumbnail} alt="Common Ground example project: warm graphic design in green and coral" width={800} height={600} priority className="aspect-[16/10] w-full object-cover" sizes="(min-width: 1024px) 480px, 90vw" /><div className="mt-4 flex items-center justify-between"><span className="display text-xl">Common Ground</span><span aria-hidden="true">↗</span></div><p className="mono mt-2 text-[10px] text-moss">PRODUCT DESIGN / RESEARCH / 2026</p><div className="mt-5 grid grid-cols-2 gap-3">{showcaseProjects.slice(1).map(project => <div key={project.id}><Image src={project.thumbnail} alt={`${project.title} example project`} width={400} height={300} className="aspect-[4/3] w-full object-cover" sizes="(min-width: 1024px) 220px, 40vw" /><p className="display mt-2 text-sm">{project.title}</p></div>)}</div></div><div className="preview-note"><span aria-hidden="true">↗</span><span>Your work.<br /><strong>Ready for the world.</strong></span></div></figure>
      </section>
      <section id="how-it-works" className="landing-container landing-section scroll-mt-8"><div className="section-heading"><div><p className="eyebrow">From a blank page to your next opportunity</p><h2 className="display mt-4 text-4xl leading-tight sm:text-5xl">A few steps.<br /><i>A whole new home for your work.</i></h2></div><p className="max-w-sm leading-7 text-moss">You bring the story. We take care of the layout. No design tools to learn, no code to write.</p></div><ol className="steps-grid">{steps.map(([title, text], index) => <li key={title}><span className="step-number mono">0{index + 1}</span><h3 className="display mt-6 text-2xl">{title}</h3><p className="mt-3 text-sm leading-7 text-moss">{text}</p></li>)}</ol><p className="mt-8 border-t border-line pt-5 text-sm leading-6 text-moss">Go at your own pace. Your draft saves on this device as you work. Preview anytime; publish when you’re ready.</p></section>
      <section id="personalize" className="personalize-section scroll-mt-8"><div className="landing-container landing-section"><div className="section-heading"><div><p className="eyebrow">More than a collection of projects</p><h2 className="display mt-4 text-4xl leading-tight sm:text-5xl">Make room for<br /><i>everything you bring.</i></h2></div><p className="max-w-sm leading-7 text-moss">A considered layout, filled with your personality. Personalize the content and images while the design stays beautifully consistent.</p></div><div className="features-grid">{features.map(([number, title, description, tags]) => <article key={number}><span className="mono text-xs text-moss">{number} /</span><h3 className="display mt-5 text-2xl">{title}</h3><p className="mt-3 text-sm leading-7 text-moss">{description}</p><p className="mono mt-6 text-[10px] uppercase tracking-wider text-moss">{tags}</p></article>)}</div></div></section>
      <section className="landing-container community-section"><CreatorCount /><div className="max-w-sm"><h2 className="display text-3xl">Good work deserves to be seen.</h2><p className="mt-3 leading-7 text-moss">Join people giving their work a home. Every published portfolio is another story out in the world.</p></div></section>
      <section className="landing-container pb-16"><div className="landing-cta"><div><p className="mono text-xs uppercase tracking-widest">100% free · Made for your next step</p><h2 className="display mt-6 text-4xl leading-tight sm:text-6xl">Your next chapter<br /><i>starts here.</i></h2><p className="mt-5 max-w-lg leading-7">Your ideas, your experience, your best work.<br />Let’s give them a place of their own.</p></div><div><Link className="btn-primary" href="/signup">Create your free portfolio <span aria-hidden="true">↗</span></Link><p className="mt-4 text-sm">Free to create. Free to publish.</p></div></div></section>
    </main><footer className="landing-container flex flex-wrap items-center justify-between gap-5 border-t border-line py-8 text-sm text-moss"><Link className="display text-xl text-ink" href="/">Portfolio studio.</Link><p>A space for your story and your work.</p><Link className="public-nav" href="/login">Sign in <span aria-hidden="true">↗</span></Link></footer>
  </div>;
}
