import Image from "next/image";
import Link from "next/link";
import ReactMarkdown from "react-markdown";
import { formatDate } from "@/lib/dates";
import type { Profile, Project } from "@/lib/types";
const address = (path: string, preview: boolean, basePath = "") => basePath === "/studio/preview" ? `${basePath}?view=${encodeURIComponent(path)}` : preview ? `/admin/preview?view=${encodeURIComponent(path)}` : `${basePath}${path === "/" ? "" : path}` || "/";
export function Biography({ children, className = "" }: { children: string; className?: string }) {
  return <div className={`markdown ${className}`}><ReactMarkdown skipHtml allowedElements={["p", "strong", "em", "ul", "ol", "li", "a", "blockquote", "br"]}>{children}</ReactMarkdown></div>;
}
function PublicHeader({ profile, preview = false, current = "/", basePath = "" }: { profile: Profile; preview?: boolean; current?: string; basePath?: string }) {
  return <header className="mx-auto flex w-full max-w-6xl flex-wrap items-center justify-between gap-4 px-6 py-6 md:px-10"><Link href={address("/", preview, basePath)} className="display max-w-[65%] break-words text-xl font-semibold tracking-tight">{profile.name}<span className="text-coral">.</span></Link><nav aria-label="Portfolio navigation" className="flex items-center gap-6 text-sm font-medium"><Link className="public-nav" aria-current={current === "/" ? "page" : undefined} href={address("/", preview, basePath)}>Work</Link><Link className="public-nav" aria-current={current === "/about" ? "page" : undefined} href={address("/about", preview, basePath)}>About</Link></nav></header>;
}
function Footer({ profile, preview }: { profile: Profile; preview: boolean }) {
  return <footer className="border-t border-line"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-5 px-6 py-8 text-sm text-moss md:px-10"><span>© {new Date().getFullYear()} {profile.name}</span><Link className="public-nav" href={preview ? "/admin/dashboard" : "/"}>{preview ? "Back to studio" : "Create your portfolio"} ↗</Link></div></footer>;
}
export function HomeView({ profile, projects, preview = false, basePath = "" }: { profile: Profile; projects: Project[]; preview?: boolean; basePath?: string }) {
  if (!profile.name && projects.length === 0) return <><header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><Link href="/" className="display text-2xl">Portfolio studio.</Link><Link className="btn-secondary" href="/login">Sign in</Link></header><main id="main-content" className="mx-auto max-w-4xl px-6 py-20 sm:py-28"><p className="eyebrow">A space for your story</p><h1 className="display mt-6 max-w-3xl text-5xl leading-tight sm:text-7xl">Your work deserves<br /><i>a place of its own.</i></h1><p className="mt-7 max-w-xl text-lg leading-8 text-moss">Create your account, tell your story, and add the work you want to share. Start with a blank portfolio and make it yours, one step at a time.</p><Link href="/signup" className="btn-primary mt-8">Create your portfolio →</Link><p className="mt-5 text-sm text-moss">No sample projects. Just your own work.</p></main></>;
  const featured = projects.find(project => project.featured);
  const remaining = projects.filter(project => project.id !== featured?.id);
  const tagline = profile.tagline ?? "Ideas, made into experiences.";
  return <><PublicHeader profile={profile} preview={preview} basePath={basePath} /><main id="main-content" className="mx-auto max-w-6xl px-6 pb-24 md:px-10">
    <section className="pb-14 pt-10 md:pb-20 md:pt-20"><p className="eyebrow mb-5">The portfolio of {profile.name}</p><h1 className="display max-w-4xl break-words text-[clamp(2.75rem,6.2vw,5.2rem)] leading-[1.06]">{tagline || profile.name}</h1>
      {profile.bannerImage && <div className="mt-9"><Image src={profile.bannerImage} alt={`Homepage banner for ${profile.name}`} width={1600} height={800} priority className="h-auto w-full rounded-sm" sizes="(min-width: 1152px) 1072px, 95vw" /></div>}

    </section>
    {featured && <section aria-label="Featured project" className="mb-16 border-y border-line py-7"><p className="eyebrow mb-5">Featured project</p><Link href={address(`/projects/${featured.slug}`, preview, basePath)} className="project-card group block"><div className="relative aspect-[4/3] overflow-hidden rounded-sm bg-line sm:aspect-[2/1]"><Image src={featured.thumbnail} alt="" fill priority={!profile.bannerImage} className="project-image object-contain" sizes="(min-width: 1152px) 1072px, 95vw" /></div><div className="mt-6 grid gap-5 md:grid-cols-2"><div><p className="mono text-xs text-moss">{formatDate(featured.date)}</p><h2 className="display mt-3 break-words text-3xl sm:text-4xl">{featured.title} <span className="text-accent" aria-hidden="true">↗</span></h2></div><div><p className="whitespace-pre-line leading-7">{featured.description}</p><p className="mt-4 text-xs leading-6 text-moss">{featured.technologies.join(" / ")}</p><span className="btn-text mt-5 inline-block">Explore project</span></div></div></Link></section>}
    {remaining.length > 0 && <><div className="mb-8 flex items-center justify-between border-t border-line pt-5"><h2 className="eyebrow">{featured ? "More work" : "Selected work"}</h2><p className="mono text-xs text-moss">{String(remaining.length).padStart(2, "0")} {remaining.length === 1 ? "project" : "projects"}</p></div><section aria-label="Projects" className="reveal-grid grid gap-x-6 gap-y-10 sm:grid-cols-2">{remaining.map(project => <Link href={address(`/projects/${project.slug}`, preview, basePath)} key={project.id} className="project-card group block min-w-0"><div className="relative aspect-[4/3] overflow-hidden rounded-sm bg-line"><Image src={project.thumbnail} alt="" fill className="project-image object-contain" sizes="(min-width: 1152px) 524px, (min-width: 640px) 45vw, 95vw" /></div><p className="mono mt-4 text-xs text-moss">{formatDate(project.date)}</p><div className="flex items-baseline justify-between gap-4 border-b border-line py-3"><h3 className="display break-words text-2xl font-semibold md:text-3xl">{project.title}</h3><span aria-hidden="true" className="text-accent">↗</span></div><p className="mt-3 text-xs leading-6 text-moss">{project.technologies.join(" / ")}</p></Link>)}</section></>}
    {!projects.length && <p className="border-y border-line py-12 text-xl text-moss">New work is on the way. Explore the About page in the meantime.</p>}
      <section aria-label="Behind the work" className="mt-14 grid gap-5 border-t border-line pt-7 md:grid-cols-[.45fr_1fr]"><p className="eyebrow">Behind the work</p><div className="max-w-2xl"><Biography className="text-lg leading-8">{profile.biography}</Biography><Link href={address("/about", preview, basePath)} className="mt-6 inline-flex border-b border-ink pb-1 text-sm font-bold">About me <span className="ml-3">↗</span></Link></div></section>
    </main><Footer profile={profile} preview={preview} /></>;
}


export function AboutView({ profile, preview = false, basePath = "" }: { profile: Profile; preview?: boolean; basePath?: string }) {
  return <><PublicHeader profile={profile} preview={preview} basePath={basePath} current="/about" /><main id="main-content" className="mx-auto max-w-6xl px-6 pb-24 md:px-10"><div className="grid gap-12 border-b border-line py-12 md:grid-cols-[.8fr_1.2fr] md:py-20"><div><p className="eyebrow mb-5">A little about me</p><h1 className="display text-[clamp(3.5rem,7vw,6rem)] leading-none">Hello,<br /><i>I&apos;m {profile.name.split(" ")[0]}.</i></h1></div>{profile.headshotImage ? <div className="relative aspect-[4/3] overflow-hidden rounded-sm md:aspect-[5/4]"><Image src={profile.headshotImage} alt={profile.name} fill priority className="object-contain" sizes="(min-width: 768px) 55vw, 95vw" /></div> : <div className="flex aspect-[4/3] items-center justify-center rounded-sm bg-[#e3e7da]"><span className="display text-8xl" aria-label={profile.name}>{profile.name.split(" ").map(word => word[0]).slice(0, 2).join("")}</span></div>}</div>
    <div className="grid gap-8 py-12 md:grid-cols-[.8fr_1.2fr] md:gap-16 md:py-16"><p className="eyebrow">My practice</p><Biography className="text-xl leading-relaxed md:text-2xl">{profile.biography || "More about my practice, coming soon."}</Biography></div>
    {(profile.education.length > 0 || profile.tools.length > 0) && <div className="grid gap-12 border-t border-line py-10 md:grid-cols-2">{profile.education.length > 0 && <section><h2 className="eyebrow mb-6">Education</h2><div className="space-y-8">{profile.education.map((item, i) => <article key={i}><h3 className="text-lg font-bold">{item.institution}</h3><p className="mt-1">{[item.degree, item.field].filter(Boolean).join(", ")}</p><p className="mt-2 text-sm text-moss">{[item.startYear, item.endYear].filter(Boolean).map(formatDate).join(" — ")}</p>{item.description && <p className="mt-3 whitespace-pre-line leading-7 text-moss">{item.description}</p>}</article>)}</div></section>}{profile.tools.length > 0 && <section><h2 className="eyebrow mb-6">Tools I use</h2><div className="flex flex-wrap gap-2">{profile.tools.map(tool => <span className="rounded-full border border-line px-3 py-1.5 text-sm" key={tool}>{tool}</span>)}</div></section>}</div>}
    {profile.jobs.length > 0 && <section className="grid gap-8 border-t border-line pt-10 md:grid-cols-[.8fr_1.2fr]"><h2 className="eyebrow">Experience</h2><div>{profile.jobs.map((job, i) => <article className="grid gap-3 border-b border-line pb-7 pt-7 first:pt-0 sm:grid-cols-[.7fr_1.3fr]" key={i}><div><p className="font-bold">{job.company}</p><p className="mono mt-2 text-xs leading-5 text-moss">{[job.startDate, job.endDate].filter(Boolean).map(formatDate).join(" — ")}</p></div><div><h3 className="display text-2xl">{job.position}</h3><p className="mt-2 whitespace-pre-line leading-7 text-moss">{job.description}</p></div></article>)}</div></section>}
    <div className="pt-12"><Link href={address("/", preview, basePath)} className="btn-text">← Back to work</Link></div></main><Footer profile={profile} preview={preview} /></>;
}
export function ProjectView({ profile, project, preview = false, basePath = "" }: { profile: Profile; project: Project; preview?: boolean; basePath?: string }) {
  return <><PublicHeader profile={profile} preview={preview} basePath={basePath} current={`/projects/${project.slug}`} /><main id="main-content" className="mx-auto max-w-6xl px-6 pb-16 md:px-10"><div className="pt-8"><Link href={address("/", preview, basePath)} className="btn-text">← All work</Link></div><header className="grid gap-8 py-12 md:grid-cols-[1.1fr_.9fr] md:items-end md:py-20"><div><p className="mono mb-5 text-xs text-moss">Case study / {formatDate(project.date)}</p><h1 className="display text-[clamp(3.5rem,7vw,6rem)] leading-[1.02]">{project.title}</h1>{project.technologies.length > 0 && <section className="mt-7 space-y-3"><h2 className="eyebrow">Scope & tools</h2><div className="flex flex-wrap gap-2">{project.technologies.map(technology => <span className="rounded-full border border-line px-3 py-1.5 text-sm" key={technology}>{technology}</span>)}</div></section>}</div><div><p className="whitespace-pre-line text-lg leading-8">{project.description}</p>{project.link && <a className="mt-7 inline-flex border-b border-ink pb-1 text-sm font-bold" href={project.link} target="_blank" rel="noopener noreferrer">Visit project <span className="ml-3" aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a>}</div></header>
    <div className="grid gap-5 md:grid-cols-2">{project.images.map((src, i) => <figure className={i === 0 ? "md:col-span-2" : ""} key={src}><Image src={src} alt={project.imageDescriptions?.[src] || `${project.title} — project image ${i + 1}`} width={1400} height={1000} priority={i === 0} className="h-auto w-full rounded-sm" sizes={i === 0 ? "95vw" : "(min-width: 768px) 45vw, 95vw"} />{project.imageDescriptions?.[src] && <figcaption className="mt-3 whitespace-pre-line text-sm leading-6 text-moss">{project.imageDescriptions[src]}</figcaption>}</figure>)}</div>
    </main><Footer profile={profile} preview={preview} /></>;
}
