import type { Profile, Project } from "./types";
export const showcaseProfile: Profile = {
  name: "Alex Morgan", tagline: "Good ideas. Thoughtfully made.", bannerImage: "/images/common-ground-detail.svg", headshotImage: "/images/mara.svg",
  biography: "I’m an independent product designer turning complex ideas into thoughtful, approachable digital experiences.\n\nMy practice connects **research, interaction design, and clear visual systems**. I work with ambitious teams to make everyday tools more useful, welcoming, and human.",
  education: [{ institution: "Northbridge School of Design", degree: "BFA", field: "Interaction Design", startYear: "2017-08-21", endYear: "2021-05-14", description: "Focused on human-centered design, visual communication, and accessible interfaces. My final project explored digital tools for stronger local communities." }],
  tools: ["Figma", "FigJam", "Adobe Illustrator", "Adobe Photoshop", "Framer", "Blender", "Visual Studio Code", "Miro"],
  jobs: [{ company: "Independent", position: "Product Designer", startDate: "2024-01-12", endDate: "Present", description: "Partnering with early-stage teams on research, product strategy, and thoughtful web and mobile experiences." }, { company: "Fieldwork Studio", position: "UX/UI Designer", startDate: "2021-06-01", endDate: "2024-01-05", description: "Designed and shipped accessible interfaces across education, community, and climate projects. Built reusable design systems and mentored junior designers." }]
};
export const showcaseProjects: Project[] = [
  { id: "showcase-common-ground", slug: "common-ground", title: "Common Ground", date: "2026-01-12", featured: true, description: "A community investment platform that helps neighbors turn shared priorities into visible, fundable action. Research, service design, and a clear contribution model bring local progress into focus.", thumbnail: "/images/common-ground.svg", images: ["/images/common-ground.svg", "/images/common-ground-detail.svg"], imageDescriptions: { "/images/common-ground.svg": "A warm, optimistic identity built around the idea of shared space.", "/images/common-ground-detail.svg": "A visual system connecting community goals with transparent progress." }, technologies: ["Figma", "Framer", "Research", "Design systems"], link: "" },
  { id: "showcase-soft-focus", slug: "soft-focus", title: "Soft Focus", date: "2025-09-18", description: "A slower, more intentional way to collect and revisit ideas. A tactile visual language and a quiet interface make room for inspiration without distraction.", thumbnail: "/images/soft-focus.svg", images: ["/images/soft-focus.svg", "/images/soft-focus-detail.svg"], imageDescriptions: { "/images/soft-focus.svg": "The collection experience pairs soft colors with a simple, deliberate hierarchy.", "/images/soft-focus-detail.svg": "Details from the interaction and visual design system." }, technologies: ["Figma", "Adobe Illustrator", "Interaction design"], link: "" },
  { id: "showcase-second-nature", slug: "second-nature", title: "Second Nature", date: "2024-04-22", description: "A mobile companion that makes everyday climate choices understandable and motivating. Research-led prompts turn household habits into small, achievable steps.", thumbnail: "/images/second-nature.svg", images: ["/images/second-nature.svg", "/images/second-nature-detail.svg"], imageDescriptions: { "/images/second-nature.svg": "An approachable palette inspired by landscapes and everyday rituals.", "/images/second-nature-detail.svg": "Supporting illustrations make progress clear at a glance." }, technologies: ["Figma", "Blender", "Mobile design", "Prototyping"], link: "" }
];
