export const SOFTWARE = {
  "Design & prototyping": ["Figma", "FigJam", "Sketch", "Adobe XD", "Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign", "Adobe Express", "Adobe Fresco", "Affinity Designer", "Affinity Photo", "Affinity Publisher", "Canva", "Framer", "ProtoPie", "Principle", "Axure RP", "Balsamiq", "Penpot", "Lunacy", "Origami Studio", "Procreate", "Krita", "GIMP", "Inkscape"],
  "3D & game development": ["Blender", "Autodesk Maya", "Autodesk 3ds Max", "Cinema 4D", "Houdini", "ZBrush", "Substance 3D Painter", "Substance 3D Designer", "Unreal Engine", "Unity", "Godot", "GameMaker", "RPG Maker", "Roblox Studio", "SketchUp", "Rhino", "Fusion 360", "SolidWorks", "AutoCAD", "Revit", "Marmoset Toolbag", "Marvelous Designer", "Aseprite"],
  "Development": ["Visual Studio Code", "Visual Studio", "IntelliJ IDEA", "PyCharm", "WebStorm", "Android Studio", "Xcode", "Sublime Text", "Vim", "Neovim", "Cursor", "Git", "GitHub", "GitLab", "Bitbucket", "GitHub Desktop", "Docker", "Postman", "Insomnia", "DBeaver", "MySQL Workbench", "TablePlus", "Terminal", "PowerShell", "Jupyter Notebook", "Anaconda", "Arduino IDE"],
  "Web & no-code": ["Webflow", "WordPress", "Squarespace", "Wix", "Shopify", "Bubble", "FlutterFlow", "Glide", "Softr", "Retool", "Zapier", "Make", "n8n", "Airtable", "Notion", "Coda", "Carrd", "Readymag", "Google AppSheet"],
  "Video, motion & audio": ["Adobe After Effects", "Adobe Premiere Pro", "DaVinci Resolve", "Final Cut Pro", "CapCut", "Adobe Animate", "Rive", "LottieFiles", "Cavalry", "Toon Boom Harmony", "Dragonframe", "OBS Studio", "Camtasia", "ScreenFlow", "Audacity", "Adobe Audition", "Ableton Live", "Logic Pro", "FL Studio", "Pro Tools", "Reaper", "GarageBand"],
  "Research & collaboration": ["Miro", "Mural", "Dovetail", "Maze", "UserTesting", "Lookback", "Optimal Workshop", "Hotjar", "Google Analytics", "Microsoft Clarity", "Typeform", "SurveyMonkey", "Qualtrics", "Google Forms", "Microsoft Forms", "Slack", "Microsoft Teams", "Zoom", "Discord", "Loom", "Confluence", "Jira", "Linear", "Asana", "Trello", "ClickUp", "Monday.com", "Basecamp"],
  "Productivity & data": ["Microsoft Word", "Microsoft Excel", "Microsoft PowerPoint", "Microsoft OneNote", "Microsoft Outlook", "Google Docs", "Google Sheets", "Google Slides", "Google Drive", "Dropbox", "Obsidian", "Evernote", "Todoist", "Tableau", "Microsoft Power BI", "Looker Studio", "SPSS", "RStudio", "MATLAB", "QGIS", "ArcGIS", "Orange", "OpenRefine"]
} as const;
export const SOFTWARE_NAMES = Object.values(SOFTWARE).flat().slice().sort((a, b) => a.localeCompare(b));
