$header = @{"Content-Type" = "application/json"}

$uri = "http://localhost:3001/api/cards"
$body = Get-Content .\Post\post_card1.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_card2.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_card3.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_card4.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_card5.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/products"
$body = Get-Content .\Post\post_product1.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_product2.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_product3.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_product4.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_product5.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/discounts"
$body = Get-Content .\Post\post_discount1.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_discount2.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_discount3.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_discount4.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_discount5.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/customers"
$body = Get-Content .\Post\post_customer1.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_customer2.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_customer3.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_customer4.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_customer5.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/transactions"
$body = Get-Content .\Post\post_transaction1.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_transaction2.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_transaction3.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_transaction4.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_transaction5.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/tags"
$body = Get-Content .\Post\post_tag1.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_tag2.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_tag3.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_tag4.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_tag5.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_tag6.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing
$body = Get-Content .\Post\post_tag7.json
$response = Invoke-WebRequest -Method Post -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/customers/1/cart"
$body = Get-Content .\Put\put_cart1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/customers/2/cart"
$body = Get-Content .\Put\put_cart2.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/customers/3/cart"
$body = Get-Content .\Put\put_cart3.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/customers/5/cardInfoIds"
$body = Get-Content .\Put\put_customerCard5.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/customers/4/cardInfoIds"
$body = Get-Content .\Put\put_customerCard4.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/customers/3/cardInfoIds"
$body = Get-Content .\Put\put_customerCard3.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/customers/1/discountIds"
$body = Get-Content .\Put\put_customerDiscount1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/customers/2/discountIds"
$body = Get-Content .\Put\put_customerDiscount2.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/customers/3/discountIds"
$body = Get-Content .\Put\put_customerDiscount3.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/discounts/1/productIds"
$body = Get-Content .\Put\put_discountProduct1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/discounts/2/productIds"
$body = Get-Content .\Put\put_discountProduct2.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/discounts/3/productIds"
$body = Get-Content .\Put\put_discountProduct3.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/discounts/4/productIds"
$body = Get-Content .\Put\put_discountProduct4.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/discounts/5/productIds"
$body = Get-Content .\Put\put_discountProduct5.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/products/1/tagIds"
$body = Get-Content .\Put\put_productTag1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/products/2/tagIds"
$body = Get-Content .\Put\put_productTag2.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/products/3/tagIds"
$body = Get-Content .\Put\put_productTag3.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/products/4/tagIds"
$body = Get-Content .\Put\put_productTag4.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/products/5/tagIds"
$body = Get-Content .\Put\put_productTag5.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/products/1/reviews"
$body = Get-Content .\Put\put_productReview1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/products/2/reviews"
$body = Get-Content .\Put\put_productReview2.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/products/3/reviews"
$body = Get-Content .\Put\put_productReview3.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/tags/1/productIds"
$body = Get-Content .\Put\put_tagProduct1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/tags/2/productIds"
$body = Get-Content .\Put\put_tagProduct2.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/tags/3/productIds"
$body = Get-Content .\Put\put_tagProduct3.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/tags/4/productIds"
$body = Get-Content .\Put\put_tagProduct4.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/tags/5/productIds"
$body = Get-Content .\Put\put_tagProduct5.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/tags/6/productIds"
$body = Get-Content .\Put\put_tagProduct6.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/tags/7/productIds"
$body = Get-Content .\Put\put_tagProduct7.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing

$uri = "http://localhost:3001/api/businessowners/"
$body = Get-Content .\Put\put_businessOwner.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/cards/"
$body = Get-Content .\Put\put_card1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/customers/"
$body = Get-Content .\Put\put_customer1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/discounts/"
$body = Get-Content .\Put\put_discount1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/products/"
$body = Get-Content .\Put\put_product1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/shops/"
$body = Get-Content .\Put\put_shop.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/tags/"
$body = Get-Content .\Put\put_tag1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing
$uri = "http://localhost:3001/api/transactions/"
$body = Get-Content .\Put\put_transaction1.json
$response = Invoke-WebRequest -Method Put -Uri $uri -Headers $header -Body $body -UseBasicParsing

