import Link from "next/link";
import Image from "next/image";
import { AdminNav } from "@/components/AdminNav";
import { ProfileEditor, DeleteProject, FeatureProject } from "@/components/AdminEditor";
import { getProfile, getProjects, getStudio } from "@/lib/content";
import { formatDate } from "@/lib/dates";
import { requireAuth } from "@/lib/auth";
export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ saved?: string; finished?: string }> }) {
  const account = await requireAuth();
  const profile = getProfile(account.id), projects = getProjects(account.id), studio = getStudio(account.id), query = await searchParams;
  return <><AdminNav /><main id="main-content" className="mx-auto max-w-6xl px-5 py-10 sm:px-8 md:py-16">
    <div className="flex flex-wrap items-end justify-between gap-5 border-b border-line pb-8"><div><p className="eyebrow">Your portfolio studio</p><h1 className="display mt-3 text-4xl sm:text-5xl">Good to see you, {profile.name.split(" ")[0]}.</h1><p className="mt-4 max-w-xl leading-7 text-moss">A space for your story and your work. Save here, preview any time, and deploy when you&apos;re ready to share.</p></div><Link className="btn-secondary" href="/admin/onboarding">{studio.completed ? "Revisit guided setup" : "Continue guided setup"} →</Link></div>
    {(query.saved || query.finished) && <p className="notice mt-6" role="status">{query.finished ? "Setup complete. Your portfolio is ready to review." : "Project saved. Your preview is up to date."}</p>}
    <p className="mt-5 text-sm text-moss">Your portfolio address: <a className="underline" href={`/u/${account.handle}`} target="_blank" rel="noreferrer">/u/{account.handle}<span className="sr-only"> (opens in a new tab)</span></a>. Available publicly after deployment</p><section className="py-10"><div className="mb-6"><p className="eyebrow">01 / About you</p><h2 className="display mt-2 text-3xl">Profile & experience</h2></div><ProfileEditor initial={profile} /></section>
    <section className="pb-12"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">02 / Selected work</p><h2 className="display mt-2 text-3xl">Your projects <span className="text-moss">({projects.length})</span></h2></div><Link href="/admin/projects/new" className="btn-primary">+ Add project</Link></div>
    <div className="space-y-4">{!projects.length && <div className="studio-panel"><h3 className="display text-2xl">Your next chapter starts here.</h3><p className="mt-3 text-moss">Add your first project to give your work a home.</p></div>}{projects.map(project => <article className="studio-panel !p-5" key={project.id}><div className="grid gap-5 sm:grid-cols-[128px_minmax(0,1fr)] sm:items-start"><div className="relative aspect-[4/3] w-full overflow-hidden rounded-lg bg-line sm:w-32 sm:shrink-0"><Image src={project.thumbnail} alt="" fill sizes="(min-width: 640px) 128px, 90vw" className="object-cover" /></div><div className="min-w-0 flex-1"><p className="mono text-xs text-moss">{formatDate(project.date)}{project.featured ? " · Featured" : ""}</p><h3 className="display mt-2 break-words text-2xl">{project.title}</h3><p className="mt-2 break-all text-xs text-moss">/projects/{project.slug} · {project.images.length} images</p></div><div className="flex flex-wrap items-center gap-3 sm:col-start-2"><Link className="btn-secondary" href={`/admin/projects/${project.id}`}>Edit <span className="sr-only">{project.title}</span>→</Link><FeatureProject id={project.id} featured={!!project.featured} /><DeleteProject id={project.id} title={project.title} /></div></div></article>)}</div></section>
    <aside className="rounded-2xl border border-line p-6"><p className="font-bold">Ready to publish?</p><p className="mt-2 max-w-3xl text-sm leading-6 text-moss">Preview your saved changes, then commit your content and images and redeploy on Vercel. Saving here updates your local files; it does not change an already deployed site.</p><Link href="/admin/preview" target="_blank" className="btn-text mt-3 inline-block">Preview the full site ↗</Link></aside>
  </main></>;
}
